spring.application.name=taskboard
spring.profiles.active=dev

# Server Port
server.port=8080

# H2 Database Config (Default for local running)
spring.datasource.url=jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
